apply plugin: 'com.android.library'

project.group = 'com.badlogicgames.gdx-controllers'

android {

    compileSdk 37

    defaultConfig {
        minSdk 24
        targetSdk 37
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']

        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lintOptions {
        abortOnError false
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    api project(":gdx-controllers-core")
}

ext {
    ARTIFACTID = 'gdx-controllers-android'
}